//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDS311_2021_03_Equipo_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int Id { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverLastName { get; set; }
        public string ReceiverAddress { get; set; }
        public string ReceiverPhoneNumber { get; set; }
        public int ProductoId { get; set; }
        public int UserId { get; set; }
        public string TimeCreated { get; set; }
        public string ETA { get; set; }
        public string Status { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual User User { get; set; }
    }
}
